### PR TITLE
Add CloudFlare errors handling

### PR DESCRIPTION
**Pull request by wvffle**
Closes #33 
Closes #29
Closes #30
Closes #31

### CODE REVIEW

**Comment by rom1504** [comment]
Looks like tests are still failing

**Comment by IdanHo** [comment]
Why are the tests testing for node v4 and v6? those are incredibly old and eol

**Comment by rom1504** [comment]
Because of https://github.com/PrismarineJS/node-yggdrasil/blob/master/.travis.yml
You can update it

**Comment by wvffle** [comment]
Ready for merging and publishing

**Comment by rom1504** [comment]
can you remove package-lock.json ? it's bad for libs

**Comment by rom1504** [comment]
note for other times : let's change the version number in package.json only in the release commit (such as https://github.com/PrismarineJS/mineflayer/commit/df51354e554339455c666b24c61228f5eb568ef3)

**Comment by wvffle** [comment]
I've done it before for my version of a package

**Pull request merged**
