### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by ahmedcader**
This PR is for the release of 1.6.2 which includes a new invalidate endpoint.

### CODE REVIEW

**Comment by rom1504** [comment]
There's a new feature so it should be 1.7.0

**Comment by ahmedcader** [comment]
@rom1504 Did you get a chance to look at this?

**Comment by u9g** [comment]
Theres way too many commits in this, please use a new branch and only update package.json and the history

**Comment by extremeheat** [comment]
The history can be squashed and merge commit renamed, shouldn’t be a problem

**Comment by extremeheat** [comment]
Ah I see it's not based on correct branch and it's PR from master branch which will make it a pain, though can be fixed:

```js
get reset --hard upstream/master
git push origin master --force
git checkout -b rel170
# make your changes...
git push origin rel170
```

then [update the branch base on this PR ](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) to `rel170` or close this PR and open a new one on that branch

**Comment by rom1504** [comment]
Please open a new PR if you want to do it

**Pull request closed without merging**
